### ISSUE TITLE
Auto-selling items that converts to other currencies than RUB will create more money than intended.

### ISSUE THREAD

**Issue by Azmereth** [dvize/SPT-TypeScript#12]
Hi there!

Relevant code there:
https://github.com/dvize/SPT-TypeScript/blob/1b3ade6d65d1da794a770a19c0b66f7bfbcc7b31/Props-AutomatedSelling/src/PAutoSell.ts#L297-L306

I noticed that when I was selling items to traders that converts into a different currency than rubles (here Peacekeeper), it will calculate wrongly the money to give back to the player.

Logs:
```
PAutoSell: Found container with label tag: junk items
Selling item Slim diary to trader Peacekeeper for 31950 USD
 and after currency exchange adjusted to 3865950 roubles
Updated sales sum for trader Peacekeeper: 81007.75
PAutoSell: Total Roubles earned: 3865950 and sent to stash
```

My hypothesis is that, from the conversion to 3.8.0, all the traders money attached to the items are converted to roubles by default.
https://db.sp-tarkov.com/search/590c651286f7741e566b6461
![image](https://github.com/dvize/SPT-TypeScript/assets/168042602/b664da11-d90f-4e90-add0-7812e7ddd121)

Calculation is as follows on my environment:
71000 (base value) * 0.45 (Peacekeeper selling markup) = 31950
31950 * 121 ([currency USD set by auto seller](https://github.com/dvize/SPT-TypeScript/blob/1b3ade6d65d1da794a770a19c0b66f7bfbcc7b31/Props-AutomatedSelling/src/PAutoSell.ts#L343)) = 3865950

Estimated fix would be to [change this multiplication to a division](https://github.com/dvize/SPT-TypeScript/blob/1b3ade6d65d1da794a770a19c0b66f7bfbcc7b31/Props-AutomatedSelling/src/PAutoSell.ts#L304) and to [change the calculation of the conversion into the logs to reflect the value calculated](https://github.com/dvize/SPT-TypeScript/blob/1b3ade6d65d1da794a770a19c0b66f7bfbcc7b31/Props-AutomatedSelling/src/PAutoSell.ts#L306).

Fix:
```
const trader = this.databaseServer.getTables().traders[traderId].base;
const price = this.traderHelper.getHighestSellToTraderPrice(item._tpl) * this.modConfig.PriceMultiplier;
const itemName = this.getItemName(item._tpl);

//need to get currency from trader and apply exchange rate
const currency = trader.currency; // "RUB", "USD", "EUR"
const exchangeRate = this.getCurrencyExchangeRate(currency);
const adjustedAmount = Math.floor(price / exchangeRate);

this.logger.info(`Selling item ${itemName} to trader ${trader.nickname} for ${adjustedAmount} ${trader.currency} \n and after currency exchange adjusted to ${price} roubles`);
```

Thanks!
An avid AutoSeller enjoyer.

**Comment by dvize** [comment]
Thanks for taking the time to writeup the issue. I will fix this tomorrow
as it should just be a simple fix.

**Comment by dvize** [comment]
resolved in latest
