### ISSUE TITLE
Auto-Seller should not create an empty stack of rubles if no items are sold

### ISSUE THREAD

**Issue by itsbeltaine** [dvize/SPT-TypeScript#14]
![image](https://github.com/dvize/SPT-TypeScript/assets/3286305/e3269b8f-8c5e-4575-bb43-2fd3d4f397d3)
![image](https://github.com/dvize/SPT-TypeScript/assets/3286305/2feb2a58-cfbf-46b0-bace-8d25d3bc9168)

https://github.com/dvize/SPT-TypeScript/blob/5beed8ee91fc35896658855547244189f4533dce/Props-AutomatedSelling/src/PAutoSell.ts#L219-L256

**Comment by dvize** [comment]
Easy fixes, but i have sent a request for you as a collaborator so you can push a change. Thanks.

**Comment by itsbeltaine** [comment]
Perfect, let me know :)
